package com.antigravity.models;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "portfolios")
public class Portfolio {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, unique = true)
    private String userId;

    // The absolutely preserved base (Initial Capital + Sum of Deposits)
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal protectedCapitalBase = BigDecimal.ZERO;

    // The trailing profits generated by the system (can be exposed to VaR/CVaR)
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal accumulatedProfit = BigDecimal.ZERO;

    @Column(nullable = false)
    private LocalDateTime lastUpdatedAt;

    public Portfolio() {}

    public Portfolio(String userId, BigDecimal initialDeposit) {
        this.userId = userId;
        this.protectedCapitalBase = initialDeposit;
        this.lastUpdatedAt = LocalDateTime.now();
    }

    public UUID getId() { return id; }
    public String getUserId() { return userId; }
    
    public BigDecimal getProtectedCapitalBase() { return protectedCapitalBase; }
    public void addDeposit(BigDecimal amount) {
        this.protectedCapitalBase = this.protectedCapitalBase.add(amount);
        this.lastUpdatedAt = LocalDateTime.now();
    }

    public BigDecimal getAccumulatedProfit() { return accumulatedProfit; }
    public void addProfit(BigDecimal amount) {
        this.accumulatedProfit = this.accumulatedProfit.add(amount);
        this.lastUpdatedAt = LocalDateTime.now();
    }
    public void deductLoss(BigDecimal amount) {
        this.accumulatedProfit = this.accumulatedProfit.subtract(amount);
        // By design, Trade Agent is never allowed to execute trades where CVaR > 10% profit.
        // The System Agent checks this constraint BEFORE execution.
        this.lastUpdatedAt = LocalDateTime.now();
    }

    public BigDecimal getTotalCurrentValue() {
        return this.protectedCapitalBase.add(this.accumulatedProfit);
    }
    
    // Process Bank Withdrawals safely
    public boolean processWithdrawal(BigDecimal requestedAmount) {
        // FRS Constraint: Withdrawals must ONLY come from profit to ensure Base is preserved.
        if (requestedAmount.compareTo(accumulatedProfit) > 0) {
            return false; // Denial: Insufficient profit margin to preserve capital base.
        }
        this.accumulatedProfit = this.accumulatedProfit.subtract(requestedAmount);
        this.lastUpdatedAt = LocalDateTime.now();
        return true;
    }

    @PreUpdate
    protected void onUpdate() {
        this.lastUpdatedAt = LocalDateTime.now();
    }
}
