package com.antigravity.models;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "portfolios")
public class Portfolio {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, unique = true)
    private String userId;

    /**
     * FRS Constraint #1: The absolutely preserved base (Initial Capital + Sum of
     * all CDS Deposits).
     * This value MUST NEVER decrease due to trading losses.
     * Increases ONLY via confirmed broker deposits (SyncCdsDeposit MCP tool).
     */
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal protectedCapitalBase = BigDecimal.ZERO;

    /**
     * Trailing profits generated by the system.
     * Only this amount may be exposed to VaR/CVaR risk bounding.
     * Only this amount may be used for withdrawals.
     */
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal accumulatedProfit = BigDecimal.ZERO;

    /**
     * Cumulative sum of all confirmed manual withdrawals (stock sells → CDS cash).
     * Tracked for UI display only. Does not affect capital preservation constraint.
     */
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal totalWithdrawals = BigDecimal.ZERO;

    @Column(nullable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime lastUpdatedAt;

    public Portfolio() {
    }

    public Portfolio(String userId, BigDecimal initialDeposit) {
        this.userId = userId;
        this.protectedCapitalBase = initialDeposit;
        this.createdAt = LocalDateTime.now();
        this.lastUpdatedAt = LocalDateTime.now();
    }

    // --- Getters ---
    public UUID getId() {
        return id;
    }

    public String getUserId() {
        return userId;
    }

    public BigDecimal getProtectedCapitalBase() {
        return protectedCapitalBase;
    }

    public BigDecimal getAccumulatedProfit() {
        return accumulatedProfit;
    }

    public BigDecimal getTotalWithdrawals() {
        return totalWithdrawals;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getLastUpdatedAt() {
        return lastUpdatedAt;
    }

    /**
     * Called when user confirms a manual CDS broker deposit.
     * Adds to the permanent, firewalled protected capital base.
     */
    public void addDeposit(BigDecimal amount) {
        this.protectedCapitalBase = this.protectedCapitalBase.add(amount);
        this.lastUpdatedAt = LocalDateTime.now();
    }

    /**
     * Called by Trade Agent when a trade generates profit.
     */
    public void addProfit(BigDecimal amount) {
        this.accumulatedProfit = this.accumulatedProfit.add(amount);
        this.lastUpdatedAt = LocalDateTime.now();
    }

    /**
     * Called by Trade Agent when a trade incurs a loss.
     * The System Agent guarantees this never exceeds 10% of accumulatedProfit via
     * CVaR constraint.
     */
    public void deductLoss(BigDecimal amount) {
        this.accumulatedProfit = this.accumulatedProfit.subtract(amount);
        this.lastUpdatedAt = LocalDateTime.now();
    }

    /**
     * FRS Constraint #1 enforcer: Withdrawal can ONLY come from accumulatedProfit.
     * If the requested amount exceeds accumulated profit, returns false.
     * Protected capital base is NEVER reduced by this operation.
     */
    public boolean processWithdrawal(BigDecimal requestedAmount) {
        if (requestedAmount.compareTo(accumulatedProfit) > 0) {
            return false;
        }
        this.accumulatedProfit = this.accumulatedProfit.subtract(requestedAmount);
        this.totalWithdrawals = this.totalWithdrawals.add(requestedAmount);
        this.lastUpdatedAt = LocalDateTime.now();
        return true;
    }

    /**
     * Returns the live total portfolio value = base + profit.
     * This represents the full notional value in the CDS account + invested
     * positions.
     */
    public BigDecimal getTotalCurrentValue() {
        return this.protectedCapitalBase.add(this.accumulatedProfit);
    }

    @PrePersist
    protected void onCreate() {
        if (this.createdAt == null)
            this.createdAt = LocalDateTime.now();
        this.lastUpdatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.lastUpdatedAt = LocalDateTime.now();
    }
}
